osx_image: xcode10.2
language: objective-c
xcode_project: RxNimble.xcodeproj
xcode_scheme:
  - RxNimbleRxBlocking
  - RxNimbleRxTest

cache:
  directories:
    - $HOME/Library/Caches/org.carthage.CarthageKit/dependencies
    - Carthage

before_install:
  - carthageversion=$(carthage version)
  - if [ $carthageversion != "0.33.0" ]; then brew uninstall carthage; HOMEBREW_NO_AUTO_UPDATE=1 brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/d453dd956dbfc5b724b0fdaeb14f9480f461479d/Formula/carthage.rb; fi

jobs:
  include:
    - stage: prepare carthage cache
      script:
        - carthage bootstrap --no-use-binaries --cache-builds
    - stage: carthage builds
      script:
        - carthage build --cache-builds --no-skip-current --platform macOS
    - script:
        - carthage build --cache-builds --no-skip-current --platform iOS
    - script:
        - carthage build --cache-builds --no-skip-current --platform tvOS

stages:
  - prepare carthage cache
  - test
  - carthage builds
